project_id = "txrhehxqroldxhfbwdth"

[functions.verify-admin]
verify_jwt = false

[functions.notify-registration]
verify_jwt = false

[functions.notify-subscription]
verify_jwt = false

[functions.send-reset-code]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false